repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        additional_dependencies: ["click"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        name: mypy-general
        args: [
          --no-strict-optional,
          --ignore-missing-imports
        ]
        additional_dependencies:
          - celery
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: flake8
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn"
          ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["."]
